server.port=8085
spring.application.name=E-Notes
spring.datasource.url=jdbc:mysql://localhost:3306/enotesproject
spring.datasource.username=root
spring.datasource.password=system@1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update

# Show SQL statements in the console
spring.jpa.show-sql=true
# Format SQL statements for better readability
spring.jpa.properties.hibernate.format_sql=true


# Enable Spring Security debug mode
#spring.security.debug=true

file.upload-dir.files=uploadsFiles

# SpringDoc OpenAPI Configuration
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true